name: worldtile_app
description: A futuristic metaverse app for buying virtual land
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_svg: ^1.1.6
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  mapbox_maps_flutter: ^2.12.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env

